version: '3'
services:
  mysql-standalone:
    image: 'mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=foreign_exchange
    ports:
      - "3307:3306"
  springboot-docker-container:
    image: fx-docker
    ports:
      - "8090:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/foreign_exchange?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
    build:
      context: "./"
      dockerfile: "Dockerfile"
    depends_on:
      - mysql-standalone
